config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'developers#index'
  resources :developers , except: :index do
    resources :bookings, only: [:new, :create]
    resources :developer_skills, only: [:new, :create]
  end
  resources :developer_skills, only: :destroy
  resource :dashboard, only: :show
  resources :bookings, only: [:show, :index] do
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :developer
  belongs_to :renter, foreign_key: :renter_id, class_name: "User"
  has_many :reviews, dependent: :destroy
  validates :project_name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true
  validate :end_date_cannot_be_before_start_date

  def end_date_cannot_be_before_start_date
    if end_date < start_date
      errors.add(:end_date, "end date cannot be before start date")
    end
  end
end

app/models/developer.rb
class Developer < ApplicationRecord
  belongs_to :owner, foreign_key: :owner_id, class_name: "User"
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :booking
  has_many :developer_skills
  has_many :skills, through: :developer_skill
  validates :name, presence: true
  has_one_attached :photo
  # include PgSearch::Model
  # pg_search_scope :search_by_specialty,
  #   against: [ :specialty ],
  #   using: {
  #     tsearch: { prefix: true }
  #   }
end

app/models/developer_skill.rb
class DeveloperSkill < ApplicationRecord
  belongs_to :developer
  belongs_to :skill
  validates :years_of_experience, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :developer, through: :booking
  has_one :user, through: :booking
  validates :title, presence: true
  validates :content, presence: true, length: { in: 3..500 }
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :developer_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, foreign_key: :renter_id, class_name: "Booking", dependent: :destroy
  has_many :developers, foreign_key: :owner_id, class_name: "Developer", dependent: :destroy
  has_many :reviews, through: :bookings
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :email, presence: true # Add REGEX Format !!!!
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  before_action :set_developer, only: [:new, :create]
  before_action :set_booking, only: :show

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.renter = current_user
    @booking.developer = @developer
    @booking.total_price = ((@booking.end_date - @booking.start_date).to_i + 1) * @developer.daily_rate
    @booking.status = "pending"
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @show_review_button_renter = @booking.status == "accepted" && current_user == @booking.renter && @booking.start_date < Date.today
    @show_review_button_owner = @booking.status == "accepted" && current_user == @booking.developer.owner && @booking.start_date < Date.today
  end

  def update
    @booking = Booking.find(params[:id])
      if @booking.update_attributes(booking_params)
        flash[:success] = "Object was successfully updated"
        redirect_to @booking
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :project_name, :status)
  end

  def set_developer
    @developer = Developer.find(params[:developer_id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @requests_accepted = Booking.all.select do |booking|
      booking.developer.owner == current_user && booking.status == "accepted"
    end
    @requests_pending = Booking.all.select do |booking|
      booking.developer.owner == current_user && booking.status == "pending"
    end
    @my_bookings_accepted = Booking.where(renter: current_user, status: 'accepted')
    @my_bookings_pending = Booking.where(renter: current_user, status: 'pending')
  end
end

app/controllers/developer_skills_controller.rb
class DeveloperSkillsController < ApplicationController
  before_action :set_developer, only: [:new, :create]
  before_action :set_skill, only: :create

  def new
    @developer_skill = DeveloperSkill.new
  end

  def create
    @developer_skill = DeveloperSkill.new(developer_skill_params)
    @developer_skill.skill = @skill
    @developer_skill.developer = @developer
    if @developer_skill.save
      redirect_to developer_path(@developer)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @developer_skill = DeveloperSkill.find(params[:id])
    @developer = @developer_skill.developer
    @developer_skill.destroy
    redirect_to developer_path(@developer)
  end

  private

  def set_developer
    @developer = Developer.find(params[:developer_id])
  end

  def set_skill
    @skill = Skill.find(params[:developer_skill][:skill_id])
  end

  def developer_skill_params
    params.require(:developer_skill).permit(:years_of_experience)
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

  before_action :set_developer, only: :show

  def index
    @specialtys = %w[PHP JS Ruby Web-Design C++ Pascal C# CSS HTML SASS jQuery Java C Python]
    if params[:query].present?
      sql_query = "\
        developers.specialty @@ :query \
        OR developers.bio @@ :query \
        "
      @developers = Developer.where(sql_query, query: "%#{params[:query]}%")
    else
      @developers = Developer.all
    end
  end

  def show
    @developer
    @reviews = Review.select do |review|
      review.developer == @developer
    end
  end

  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)
    @developer.owner = current_user
    if @developer.save
      redirect_to developer_path(@developer)
    else
      render :new
    end
  end

  private

  def set_developer
    @developer = Developer.find(params[:id])
  end

  def developer_params
    params.require(:developer).permit(:name, :specialty, :age, :bio, :daily_rate, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="margin-top">Your booking for <%= @developer.name %>:</h1>
  </div>
  <div class="row">
    <h3 class="margin-top">Daily rate: $<%=@developer.daily_rate %></h3>
  </div>
  <div class="form margin-top">
    <%= simple_form_for [@developer, @booking] do |f| %>
      <%= f.input :project_name %>
      <%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>
      <%= f.submit "Book the developer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="custom-container">
  <div class="row">
    <div class="col-12">
      <h1 class="title margin-top margin-bottom">Your booking with <%= link_to @booking.developer.name, developer_path(@booking.developer) %></h1>
    </div>
  </div>
</div>
<div class="custom-container justify-space-between">
  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="summary">
        <h4>Summary :</h4>
        <div class="info-summary">
          <p><strong>Status</strong>: <%= @booking.status.capitalize %></p>
          <p><strong>Dates</strong>: <%= @booking.start_date.strftime("%B %d, %Y") %> <strong>To</strong> <%= @booking.end_date.strftime("%B %d, %Y") %></p>
          <p><strong>Total price</strong>: $<%= @booking.total_price %></p>
          <p><strong>Project name</strong>: <%= @booking.project_name %></p>
          <p><strong>Developer Owner</strong>: <%= @booking.developer.owner.name %></p>


          <% if @booking.status == "pending" && @booking.developer.owner == current_user %>
            <div class="action-buttons">
              <div class="buttons">

                <%= simple_form_for @booking do |f| %>
                <%= f.input :status, input_html: { value: "Accepted" }, as: :hidden %>
                <%= f.submit "Accept", class:"accept-booking" %>
                <% end %>

                <div class="blank">
                </div>

                <%= simple_form_for @booking do |f| %>
                <%= f.input :status, input_html: { value: "Rejected" }, as: :hidden %>
                <%= f.submit "Reject", class:"reject-booking" %>
                <% end %>

              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-lg-1">
    </div>
    <div class="col-12 col-lg-5">
      <div id="review-area">
        <% if @show_review_button_renter %>
        <%= link_to "Write a renter review", new_booking_review_path(@booking), class: "add-review-button" %> <br>
        <% elsif @show_review_button_owner %>
        <%= link_to "Write an owner review", new_booking_review_path(@booking), class: "add-review-button" %> <br>
        <% else %>
          <p class="add-review-button">You can't add a review</p>
        <% end %>
      </div>
      <h4><%= pluralize @booking.reviews.count, "Review" %> :</h4>
      <% @booking.reviews.reverse.each do |review| %>
      <div class="review">
        <div class="review-title">
          <h5><%= review.title %></h5>
          <div class="author">
            - by <%= current_user.name.split[0] %>
            <% if current_user == @booking.developer.owner %>
            (Owner)
            <% elsif current_user == @booking.renter %>
            (Renter)
            <% end %>
          </div>
          <div class="review-date">
            <%= review.created_at.strftime("%B %d, %Y, %I:%M %p") %>
          </div>
        </div>
        <% review.rating.times do %>
        <i class="fas fa-star" style="color:#ffd43d"></i>
        <% end %>
        <% (5-review.rating).times do %>
        <i class="far fa-star" style="color:#bcb6c1"></i>
        <% end %>
        <p><%= review.content %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/show.html.erb
<% @title_content = "My dashboard" %>
<%#= @renter.name %>
<%= render "layouts/header_for_index", locals: { title_content: @title_content } %>
  <div class="row px-4">
    <div class="col-6 bg-info">
      <% @title_content = "My offers" %>
      <%= render "layouts/header_for_index", locals: { title_content: @title_content } %>
      <% @title_content = "My offers" %>
      <h6>Accepted: <%= @requests_accepted.count %> </h6>
      <%= render 'layouts/bookings_form', locals: {
        bookings: @bookings = @requests_accepted
        } %>
      <hr>
      <h6>Pending: <%= @requests_pending.count %> </h6>
      <%= render 'layouts/bookings_form', locals: {
        bookings: @bookings = @requests_pending
        } %>
    </div>  
    <div class="col-6 bg-success">
      <% @title_content = "My current bookings" %>
      <%= render "layouts/header_for_index", locals: { title_content: @title_content } %>
      <h6>Accepted: <%= @my_bookings_accepted.count %> </h6>
      <%= render 'layouts/bookings_form', locals: {
        bookings: @bookings = @my_bookings_accepted
        } %>
      <hr>
      <h6>Pending: <%= @my_bookings_pending.count %> </h6>
      <%= render 'layouts/bookings_form', locals: {
        bookings: @bookings = @my_bookings_pending
        } %>
    </div>
  </div>

app/views/developer_skills/new.html.erb
<div class="container ">
  <div class="row justify-content-center">
    <h1 class="margin-top">Add a skill</h1>
  </div>
  <div class="row justify-content-center">
    <div class="form margin-top">
      <%= simple_form_for [@developer, @developer_skill] do |f| %>
        <%= f.association :skill %>
        <%= f.input :years_of_experience %>
        <%= f.submit "Add developer skill", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/developers/index.html.erb
<div class="main-container">
  <% @title_content = "All developers" %>

  <div class="row">
    <div class="col-3 ">
      <div class="developer-search w-25">
        <%= form_tag root_path, method: :get do %>
          <%= 
            text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a developer"
          %>

          <ul class="">
            <% @specialtys.each do |specialty| %>
              <li>
                <%= check_box_tag 'query', specialty %>
                <%= "#{specialty}" %>
              </li>
            <% end %>
          </ul>

          <%= submit_tag "Search", class: "btn btn-block purple" %>
        <% end %>
      </div>
    </div>

    <div class="col-9">
      <%= link_to "Add developer", new_developer_path, class: "btn purple mt-1 ml-3" %>
      <%= render "layouts/header_for_index", locals: { title_content: @title_content } %>
      <%= render 'layouts/developers_index' %>
    </div>
  </div>
</div>

app/views/developers/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="margin-top">Create your developer</h1>
  </div>
  <div class="row justify-content-center">
    <div class="form margin-top">
      <%= simple_form_for @developer do |f| %>
        <%= f.input :name %>
        <%= f.input :specialty %>
        <%= f.input :age %>
        <%= f.input :bio %>
        <%= f.input :daily_rate %>
         <div class="form-group">
        <%= f.input :photo, as: :file %>
        <%= f.submit "Create profile", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/developers/show.html.erb
<div class="container-dev">
  <div class="wrapper">
    <div class="profile"> 
      <% if @developer.photo.attached? %>
        <%= cl_image_tag @developer.photo.key, class: "thumbnail" %>  
      <% end %>
      <h4 class="name"><%= @developer.name %></h4>
      <p class="title">Profile</p>
      <p class="title">$<%= @developer.daily_rate %></p>
      <p class="description"><%= @developer.bio %></p>

      <p>
        Language:
        <% if current_user == @developer.owner %>
          <%= link_to "+", new_developer_developer_skill_path(@developer) %>
        <% end %>
      </p>
      <p>
        <% @developer.developer_skills.each do |developer_skill| %>
          <%= developer_skill.skill.name %> - <%= developer_skill.years_of_experience %> years
          <% if current_user == @developer.owner %>
            <%= link_to developer_skill_path(developer_skill), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          <% end %>
        <br>
        <% end %>
      </p>
      <%#= link_to "Book", new_developer_booking_path(@developer), class: "btn" %>
      <%#= link_to "Hire developer", new_developer_booking_path(@developer)%>
  

  <div class="social-icons">
		<div class="icon">
			<a href="/"><i class="fab fa-dribbble"></i></a>
		</div>
		
		<div class="icon">
			<a href="#"><i class="fab fa-behance"></i></a>
		</div>
    <div>
    <%= link_to "Book", new_developer_booking_path(@developer), class: "btn" %>
    </div>
  </div>
  <% if !@reviews.empty? %>
        <% @reviews.each do |review| %>
          <h5><%= review.title %></h5>
            <% review.rating.times do %>
              <i class="fas fa-star" style="color:#ffd43d"></i>
            <% end %>
            <% (5-review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          <p><%= review.content %></p>
          <br>
        <% end %>
      <% else %>
        <p>No reviews on this developer yet</p>
      <% end %>
  </div>
  
</div>
</div>

app/views/layouts/_bookings_form.html.erb
  <div class="row d-flex justify-content-center"> 
    <% @bookings.each do |booking| %>
      <div class="col-12">
        <div class="card" style="">
          <%# <img src="..." class="card-img-top" alt="..."> %>
          <div class="card-body">
            <p><%= link_to booking.project_name, booking %></h4>
            <p>Price: $<%= booking.total_price %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div> 

app/views/layouts/_developers_index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center"> 
    <% @developers.each do |developer| %>
      <div class="col-lg-4 my-1">
        <div class="card-developer" style="">
          <div class="row">
            <div class="col-4 d-flex align-items-center">
              <% if developer.photo.attached? %>
                <%= cl_image_tag developer.photo.key, height: 80, width: 80, crop: :fit, class: "avatar w-100" %>
              <% end %>
            </div>
            <div class="col-8">
              <div class="">
                <div class="developer-card-title text-nowrap"><%= "#{developer.name}" %></div>
                <p class="developer-card-text"> <%= developer.specialty %></p>
                <p class="developer-card-text">Price per day: $<%= developer.daily_rate %></p>
                <%= link_to "See details", developer, class: "btn purple" %>
                <p></p>
              </div>
            </div>
          </div>
        </div>



      </div>
    <% end %>
  </div> 
</div>

app/views/layouts/_header_for_index.html.erb
<h1 class="header_for_index text-center my-5"><%= @title_content %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="container ">
  <div class="row justify-content-center">
    <h1 class="margin-top">Write a review</h1>
  </div>
  <div class="row justify-content-center">
    <div class="form margin-top">
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a %>
        <%= f.submit "Post review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active margin-left">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown margin-left">
          <%= link_to "DASHBOARD", dashboard_path %>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Dashboard", "user_path", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>